language: node_js

sudu: false
node_js:
  - 14

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

scripts:
  - yarn test
